version: '3.8'
services:
  gatekeeper-gateway:
    build: ./gatekeeper-gateway
    ports:
      - "8080:8080"
    environment:
      - BACKEND_API=http://gatekeeper-server:8000
    volumes:
      - ./gatekeeper-gateway/plugins:/app/plugins
      - ./gatekeeper-gateway/schemas:/app/schemas
      - ./gatekeeper-gateway/config.yaml:/app/config.yaml
      - ./gatekeeper-gateway/opa:/app/opa
    depends_on:
      - gatekeeper-server
      - opa

  gatekeeper-server:
    build: ./gatekeeper-server
    ports:
      - "8000:8000"

  gatekeeper-client:
    build: ./gatekeeper-client
    depends_on:
      - gatekeeper-gateway

  opa:
    image: openpolicyagent/opa:latest
    command: ["run", "--server", "/app/opa/enterprise_policy.rego"]
    volumes:
      - ./gatekeeper-gateway/opa:/app/opa
    ports:
      - "8181:8181"
