services:
  gatekeeper-gateway:
    build: ./gatekeeper-gateway
    ports:
      - "8080:8080"
    environment:
      - BACKEND_API=http://gatekeeper-server:8000
      - OPA_URL=http://opa:8181/v1/data/enterprise/policy # Add OPA URL for easy configuration
    volumes:
      - ./gatekeeper-gateway/plugins:/app/plugins
      - ./gatekeeper-gateway/schemas:/app/schemas
      - ./gatekeeper-gateway/config.yaml:/app/config.yaml
      - ./gatekeeper-gateway/opa:/app/opa
    depends_on:
      - gatekeeper-server
      - opa
    mem_limit: 4g

  gatekeeper-server:
    build: ./gatekeeper-server
    ports:
      - "8000:8000"
    mem_limit: 2g

  gatekeeper-client:
    build: ./gatekeeper-client
    depends_on:
      - gatekeeper-gateway
    mem_limit: 1g

  opa:
    build:
      context: .
      dockerfile: Dockerfile.opa
      platforms:
        - linux/arm64
    command: [
      "run", 
      "--server", 
      "--addr=0.0.0.0:8181",
      "--log-level=debug",
      "/app/opa"  # Add this line to load policies from the mounted directory
    ]
    volumes:
      - ./gatekeeper-gateway/opa:/app/opa:ro
    ports:
      - "8181:8181"
      - "8282:8282"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8282/health || curl -f http://localhost:8181/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    mem_limit: 512m