openapi: 3.1.0
info:
  title: GateKeeperMCP Gateway API
  version: "1.0"
paths:
  /execute_mcp:
    post:
      summary: "Execute a structured MCP command"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MCPCommand'
      responses:
        "200":
          description: Command processed
          content:
            application/json:
              schema:
                type: object
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
components:
  schemas:
    MCPCommand:
      type: object
      properties:
        action:
          type: string
        parameters:
          type: object
          additionalProperties: true
        user:
          type: string
        metadata:
          type: object
          additionalProperties: true
      required:
        - action
        - parameters
